apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . | quote }}
imagePullSecrets:
{{ toYaml .Values.rbac.imagePullSecrets | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "name" . | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - redis.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "name" . | quote }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" . | quote }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "name" . | quote }}
  apiGroup: rbac.authorization.k8s.io
  