apiVersion: redis.io/v1alpha1
kind: Redis
metadata:
  name: example-pod-anty-affinity
spec:
  sentinel:
    replicas: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: security
                    operator: In
                    values:
                      - us-west-1
              topologyKey: failure-domain.beta.kubernetes.io/zone
  redis:
    replicas: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: security
                    operator: In
                    values:
                      - us-west-1
              topologyKey: failure-domain.beta.kubernetes.io/zone
