apiVersion: redis.io/v1alpha1
kind: Redis
metadata:
  name: example-tolerations
spec:
  redis:
    replicas: 3
    tolerations:
      - effect: NoExecute
        key: dedicated
        operator: Equal
        value: production
  sentinel:
    replicas: 3
    tolerations:
      - effect: NoExecute
        key: dedicated
        operator: Equal
        value: production
